version: '3'

services:
  elevatorx:
    build: .
    volumes:
      - .:/www/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=elevatorx
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: elevatorx
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  data: