# Generated by Django 4.2.1 on 2023-05-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_from_floor', models.IntegerField()),
                ('requested_to_floor', models.IntegerField()),
                ('is_serviced', models.BooleanField(default=False)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
            options={
                'verbose_name_plural': 'elevator_requests',
                'db_table': 'elevator_request',
                'ordering': ['elevator'],
            },
        ),
    ]
