# Generated by Django 4.2.1 on 2023-05-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_elevatorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=100)),
                ('number_of_elevators', models.IntegerField(default=1)),
                ('number_of_floors', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'elevator_systems',
                'db_table': 'elevator_system',
                'ordering': ['number_of_elevators'],
            },
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.elevatorsystem'),
            preserve_default=False,
        ),
    ]
