# Generated by Django 4.2.1 on 2023-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elevatorsystem_elevator_elevator_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=1),
        ),
    ]
