# Generated by Django 4.2.1 on 2023-05-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequest',
            name='is_serviced',
            field=models.BooleanField(default=True),
        ),
    ]
